apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
      containers:
        - name: mainapp-tick
          image: josephshih13/tick
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /home/ec2-user/environment
        - name: mainapp-backend
          image: josephshih13/mainapp2
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /home/ec2-user/environment