apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      volumes: # Define volume
        - name: shared-image
          persistentVolumeClaim:
            claimName: image-claim
      containers:
        - name: mainapp-tick
          image: josephshih13/tick
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /home/ec2-user/environment
        - name: mainapp-backend
          image: josephshih13/mainapp2
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /home/ec2-user/environment
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mainapp-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: mainapp-svc
          servicePort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: mainapp-svc
spec:
  type: ClusterIP
  selector:
    app: mainapp
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 9936
